### ISSUE TITLE
Direct Access causes 500 error

### ISSUE THREAD

**Issue by benhartwich** [rmbinder/DeclarationOfMembership#8]
Hi,

if I access the page with declaration of membership directly I get a 500 php error:

`2022/11/04 07:42:59 [error] 824#824: *94902 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught AdmException: No url within the navigation stack. in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Navigation.php:148
Stack trace:
#0 /var/www/verwaltung/htdocs/admidio/adm_plugins/declaration-of-membership/declaration_of_membership.php(65): Navigation->getUrl()
#1 {main}
  thrown in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Navigation.php on line 148" while reading response header from upstream, client: 91.114.81.36, server: verwaltung.astronomie.at, request: "GET /adm_plugins/declaration-of-membership/declaration_of_membership.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm-verwaltung.sock:", host: "verwaltung.astronomie.at"
`

Is this any kind of webserver missconfiguration or a bug? I am using nginx with php 7.4.

**Comment by rmbinder** [comment]
This is probably a bug with the URL stack.

I also linked directly to the PHP file earlier. Since a certain Admidio update (but I don't remember which one) this no longer works. I'm currently still working on the (new) documentation of membership fee. Then I start again with the issues of the plugins.
